### ISSUE TITLE
ImpactUtilities.groovy - null pointer exception in updateCollection on "Outputs" collection

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb-zappbuild#330] opened 2023-03-13 22:02 UTC
Hi,

In the `updateCollection` function of the `ImpactUtilities.groovy` script, action `deletedFiles.each`, an exception is raised on the line

`metadataStore.getCollection(props.applicationOutputsCollectionName).deleteLogicalFile(logicalFile)`

A priori the "Outputs" Collection does not exist and the `getCollection` function returns the value null, so we cannot chain the `deleteLogicalFile` function in a chained way.

Thanks.

![image](https://user-images.githubusercontent.com/63861965/224842004-dfdb5e17-e0f3-44a0-a059-d51e322755e1.png)

**Comment by dennis-behm** [comment] 2023-03-16 13:20
@FALLAI-Denis 

Is this null pointer caused by a customisation of yours to skip creating the `applicationOutputsCollection`?

In [ImpactUtilities.verifyCollections()](https://github.com/IBM/dbb-zappbuild/blob/5a649f0a591625be0bfe39dd880ef1d43ba8272f/utilities/ImpactUtilities.groovy#L954), the collection will always be created.

**Comment by dennis-behm** [comment] 2023-03-20 11:33
@FALLAI-Denis 

I was able to reproduce your problem. It is not about the collection, it is about the case, when the logicalFile does not exist.

I believe the new DBB toolkit is too strict here .

**Comment by dennis-behm** [comment] 2023-11-23 18:11
Closing the issue. Resolved as part of the DBB toolkit ptfs

**Closed by dennis-behm** 2023-11-23 18:11 UTC
Labels: bug
